### ISSUE TITLE
Rendering issues when used with Bootstrap-Vue tabs

### ISSUE THREAD

**Issue by panchofrank** [fullcalendar/fullcalendar-vue#146] opened 2021-02-07 19:23 UTC
The calendar doesn't seem to display correctly when used with bootstrap-vue and it is nested in a tab.  Is this a known issue?  Is there a workaround?
Here is an [example](https://codesandbox.io/s/infallible-meadow-eybez) in a sandbox.

**Comment by acerix** [comment] 2021-02-10 19:41
It seems the issue is that the calendar is rendered while it is still hidden,  can be fixed by calling `updateSize` after it is displayed, or after a short timeout if that not possible.

https://fullcalendar.io/docs/updateSize

**Closed by acerix** 2021-02-10 19:41 UTC

**Comment by panchofrank** [comment] 2021-02-10 19:58
Thanks - I'll try this workaround.  Wouldn't it be possible to for the fullcalendar-vue connector to this automatically in a future release?

**Comment by acerix** [comment] 2021-02-10 20:01
I think that's not possible since the connector doesn't know when the tab is displayed.

**Comment by panchofrank** [comment] 2021-02-11 21:02
In case anyone else comes across this, the solution to make the calendar load only once the tab is active is to make the tab 'lazy'.  Here's a working [solution](https://codesandbox.io/s/naughty-currying-xdr3z?file=/src/DemoApp.vue)

**Comment by laurensiusadi** [comment] 2021-03-12 07:21
![sidebar-hide](https://user-images.githubusercontent.com/5661040/110906141-21032f80-833e-11eb-89b4-60442ffd902c.gif)

I'm using the calendar component with a sidebar layout like the [example project](https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/vue?file=/src/DemoApp.vue)

When I hide the sidebar, the calendar inner width doesn't automatically update.

So do I need to use `updateSize`?
