### ISSUE TITLE
Can we render a vue component on render callbacks? e.g. eventRender

### ISSUE THREAD

**Issue by anyb1s** [fullcalendar/fullcalendar-vue#42] opened 2019-07-26 06:27 UTC
Is it possible to render vue component upon render callbacks?
E.g. eventRender to render a custom vue component?

**Comment by acerix** [comment] 2019-07-26 19:39
Do you mean as described here?

https://css-tricks.com/creating-vue-js-component-instances-programmatically/

I don't see any reason that wouldn't be possible.

**Comment by azhard4int** [comment] 2019-09-16 19:43
@anyb1s Here is an example of how we did it for our application:

```
 renderCalendarItem (item) {
      let el = Vue.compile(`<calendar-item :item="item"></calendar-item>`)
      el = new Vue({
        components: {
          CalendarItem
        },
        data () {
          return {
            item: item
          }
        },
        router,
        store,
        render: el.render,
        staticRenderFns:
          el.staticRenderFns
      }).$mount()
      return el.$el.innerHTML
    },
```

**Comment by denys-vladymyrov** [comment] 2019-12-03 09:58
Another situation, guys. What if i have already a VueJs component in a separate file?
For example, i have separate component "View Mode", it's a 3 buttons that change View mode but i created separate component for them. 
So i import it inside Parent component there Fullcalendar is located. 

As a result i have this in template

     <template>
          <div>
             <ViewMode></ViewMode>
             <FullCalendar .../>
          </div>
     </template>

**But i don't need to insert "ViewMode" in template** because i have to have "ViewMode" **inside "Fullcalendar" HEADER**

For now i just move my "ViewMode" component inside "Fullcalendar" **using appendChild()** in "viewSkeletonRender" method.  **It works but it only works if i don't send ANY Props inside "ViewMode"**

   If i send even 1 prop like <ViewMode :calendarApi="calApi"></ViewMode> in this case  during appendChild() **this component will be removed from DOM totally** 

I got out of this position using VUEX and not sending any props inside "ViewMode". 
But really interesting why it happens.

**Comment by jgujgu** [comment] 2019-12-10 23:18
@denys-vladymyrov Have you considered doing this? I don't know if this will be my final implementation, but I had luck mounting a single file component (`AppTimeGridHeader` in this case) then inserting its html contents into the correct spot. I tried inserting props without a problem. I guess the only major way it differs from your implementation is by hiding it completely from view, so it never goes away.

```js
<template lang="pug">
  .vue-app-time-grid
    div(style="display:none;")
      AppTimeGridHeader(ref='appTimeGridHeader')
    FullCalendar(
      default-view="timeGridWeek"
      :dates-render="datesRender"
    )
</template>
<script>
import FullCalendar from '@fullcalendar/vue';
import timeGridPlugin from '@fullcalendar/timegrid';

export default {
  name: 'AppTimeGrid',
  components: {
    FullCalendar
  },
  methods: {
    datesRender(info) {
      info.view.header.el.innerHTML = this.$refs.appTimeGridHeader.$el.outerHTML;
    },
  }
};
</script>
```

**Comment by denis-pujdak-adm-it** [comment] 2019-12-19 12:44
Can we just implement an event template as a slot?
eg.
```
<full-calendar>
  <template v-slot:event="slotProps">
     {{ slotProps.event.title }}
  </template>
</full-calendar>
```
or
```
<full-calendar>
  <template v-slot:event="slotProps">
     <calendar-item :item="slotProps.event"></calendar-item>
  </template>
</full-calendar>
```

**Comment by denys-vladymyrov** [comment] 2019-12-20 09:35
> @denys-vladymyrov Have you considered doing this? I don't know if this will be my final implementation, but I had luck mounting a single file component (`AppTimeGridHeader` in this case) then inserting its html contents into the correct spot. I tried inserting props without a problem. I guess the only major way it differs from your implementation is by hiding it completely from view, so it never goes away.
> 
> Edit: I added destroy so it does not persist on the dom.
> 
> ```js
> <template lang="pug">
>   .vue-app-time-grid
>     div(style="display:none;")
>       AppTimeGridHeader(ref='appTimeGridHeader')
>     FullCalendar(
>       default-view="timeGridWeek"
>       :dates-render="datesRender"
>     )
> </template>
> <script>
> import FullCalendar from '@fullcalendar/vue';
> import timeGridPlugin from '@fullcalendar/timegrid';
> 
> export default {
>   name: 'AppTimeGrid',
>   components: {
>     FullCalendar
>   },
>   methods: {
>     datesRender(info) {
>       info.view.header.el.innerHTML = this.$refs.appTimeGridHeader.$el.outerHTML;
> this.$refs.appTimeGridHeader.$destroy();
>     },
>   }
> };
> </script>
> ```
> 
> ```js
> <template lang="pug">
>   table.app-time-grid-header
>     thead
>       tr
>         //Header changes
> </template>
> <script>
> export default {
>   name: 'AppTimeGridHeader',
>   props: {
>     dates: {
>       type: Array,
>       default: () => []
>     }
>   },
>   destroyed() {
>     this.$el.parentNode.removeChild(this.$el);
>   }
> };
> </script>
> ```
> 
> Edit 2:
> The methodology outlined in the linked example works just fine
> 
> ```js
> import Button from 'Button.vue'
> import Vue from 'vue'
> var ComponentClass = Vue.extend(Button)
> var instance = new ComponentClass({
>     propsData: { type: 'primary' }
> })
> instance.$mount() // pass nothing
> this.$refs.container.appendChild(instance.$el)
> //I have this instead
> info.view.header.el.innerHTML = instance.$el.outerHTML;
> ```

@jgujgu  Yes, i think your solution will work because you use "datesRender" hook and each time you change "View" or "Date" in your calendar this hook will be invoked. 
But anyway there is a chance that fullcalendar is going to be re-rendered without calling that hook and you will lose your component that you moved into header.

My personal opinion for fullcalendar header is that **if you need to add something custom there, just create your own header**. I did that and it is not difficult, fullcalendar API provides all what we need for that without any issues.

**Comment by arshaw** [comment] 2020-04-03 17:01
I'm considering this a duplicate of
https://github.com/fullcalendar/fullcalendar-vue/issues/14
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

v5 beta will be release on monday which has this feature

**Closed by arshaw** 2020-04-03 17:01 UTC
Labels: Discussing
