### ISSUE TITLE
Resources and events created as Vue data are not loaded correctly

### ISSUE THREAD

**Issue by notronwest** [fullcalendar/fullcalendar-vue#96] opened 2020-06-24 14:01 UTC
When you provide resources: this.myResources or events: this.myEvents they are not loaded into the calendar.

https://codesandbox.io/s/blissful-morse-3ls2u?file=/src/DemoApp.vue

If you replace the variables with direct data in calendarOptions you will see them load correctly

**Comment by acerix** [comment] 2020-06-25 18:45
The issue is that `myEvents` and `myResources` are defined at the same time as the calendar options so the values are still `undefined` when you are setting them.  To set them like that, you could return them from a method:

https://codesandbox.io/s/practical-goldwasser-6gg7y?file=/src/DemoApp.vue

**Comment by notronwest** [comment] 2020-06-29 16:52
That approach is fine if the data is static. But in our case the resources and events are being loaded dynamically from data that isn't available immediately when the component loads. 

Also, this worked fine in v4. So something has changed during the upgrade. 

Shouldn't you be able to do something like this:

options: {
  initialResources: [],
  resources: this.resources
  ....
}

And then, when the model changes and this.resources has value the calendar is updated?

**Comment by notronwest** [comment] 2020-06-29 17:50
A simple example of this would be:

https://codesandbox.io/s/pedantic-curran-6sk76?file=/src/DemoApp.vue

**Comment by acerix** [comment] 2020-06-29 18:21
I didn't know Vue's data can do that, seeing how it worked in v4, the same should still be possible in v5, so it does seem like a bug then.

For now, it works to pass the function directly, eg:

https://codesandbox.io/s/hungry-bash-gl94l

**Comment by notronwest** [comment] 2020-06-29 18:35
I updated my example to be as close to an example of what we have working in 4.0.

https://codesandbox.io/s/pedantic-curran-6sk76?file=/src/DemoApp.vue

Whenever this.criteriaRequired changes, I would expect FullCalendar to recall the function to getEvents (or Resources)

**Comment by jambrose42** [comment] 2020-07-03 02:47
Do I understand correctly that there is no way to get and / or update events via a method that returns data asynchronously?  

I'm looking to get events via a function to make use of the `info` parameter, but there does not seem to be a way to call a method such as this.getEvents(info).

Am I missing something basic?

**Comment by hvekriya** [comment] 2020-07-08 11:26
I am having a similar problem. I am using vuex store and in there I have events being loaded via the Firestore.
Struggling to load this data into calendar. I have manged to load it when the update life cycle is called. Not before. But the problem is that events get loaded onto calendar multiple times everytime there's an update. 

When trying to load in the mount lifecycle it wont work because data isn't available.

**Comment by astyltsvig** [comment] 2020-07-11 19:52
And it looks like you're not longer able to bind the data to a computed property. 

It is really annoying :(

**Comment by drcodemonster** [comment] 2020-07-14 12:19
As stated here [https://fullcalendar.io/docs/dynamic-options](url)
 ... dynamic setting of the following options is not applicable:

events
eventSources ....


Therefore, for those unable to load events from a computed property or from props, here is the solution to load them dynamically: First in template you have to give it a ref name . and then, for example in the mount hook , you have to code as below. Hope it helps.. 

`<template>
  <div>
    <FullCalendar
      ref="fullCalendar"
      :options="calendarOptions"
    >
      <template v-slot:eventContent="arg">
        <b>{{ arg.timeText }}</b>
        <i>{{ arg.event.title }}</i>
      </template>
    </FullCalendar>
  </div>
</template>`
.....
  props: {
    calenderEvents: {
      type: [Array, Object],
      default: () => [{ title: '', date: '' }],
    },
  },
....
mounted() {
const calendarApi = this.$refs.fullCalendar.getApi();
calendarApi.addEventSource(this.calenderEvents);
}

**Comment by arshaw** [comment] 2020-07-22 20:37
@notronwest, looking at your [most recent codepen](https://codesandbox.io/s/pedantic-curran-6sk76?file=/src/DemoApp.vue), I see two problems:

1. you can't do `events: this.myEvents` when `myEvents` isn't yet defined during the initial render
2. you can't read `this.criteriaRequired` because the `getMyResources` function is an arrow-style function, which Vue doesn't allow for methods

@jambrose42, the simple answer it to return a promise or use the `successCallback` of an [events function](https://fullcalendar.io/docs/events-function)

@hvekriya, I have no idea why your code isn't working, but please take a look at the [Vuex example project](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/vue-vuex)

@astyltsvig the [tests that are related to computed properties](https://github.com/fullcalendar/fullcalendar-vue/blob/v5.1.0/tests/main.js#L327-L359) are passing, so there must be something else going wrong. We'll never know without a recreation.

@drcodemonster thank you for bringing this up, but for declarative frameworks like Vue and React, it's actually not true, it's possible to re-set these declaratively. I made a note to update the docs.

Since this ticket has become a dumping ground for unrelated issues, I'm closing.

**Closed by arshaw** 2020-07-22 20:37 UTC
Labels: Confirmed

**Comment by lllopo** [comment] 2020-08-27 14:44
@arshaw I don't see why closed this ? There is an issue and I believe there is an issue because it is wrong by design in FC5. Even before I describe the problem, let me tell you - you mention in the migration guide, that the new approach of setting options is more consistent and generally better. It might be more consistent with the non-Vue FC, but from my point of view as a Vue guy - it is totally bad ... and as it seems - not working, which is something to be expected and below I'll explain why.

Basically - the FC Vue options are not really fully reactive any more. The issue comes mostly with attaching computed properties as FC options. in FC4 this was first straightforward and secondly - working. In FC5 - none of the above. 
In FC5 :
- If you assemble the FC options in the data() method - it throws undefines, of course.
- If you assemble it in mounted(), even if you use this.$set(), still the computed properties remain not reactive, although initially properly set. Don't know why, but it's a tested fact. I don't know what test you have on that, but in the real world it fails.
- If you do it as in your Vuex example, as computed property itself - there is a **biiiig** problem - both in usability and performance. 

Here's the thing, the way I see it - what you did in the Vuex example is converting all the FC options to one big computed property. This means - on **any change** of a reactive property within the options, **all options get reset**. This is terribly awful by many aspects (especially performance), but the worst one is, that there is no more events caching in certain cases. 

Example :
I have resources stored in Vuex store and events coming from an ajax source. 
The resources can be filtered by the user and because the Vuex property is (was) reactive and bound both to FC resources and the filter box, in FC 4, this automatically was removing the events for the filtered out resources from the list (through some stuff in the events rendering list), without triggering events reloads from the server. 
Now in FC5 this is screwed, first by the fact that eventContent cannot return false any more, like eventRender did (total and inexplicable nightmare), but anyway - mostly because FC Vue is not really reactive anymore. When I change the resources all FC options get reset (as the full options are a computed property) and so - the events source along with everything else. Because of that - on any resources change - the events get reloaded from the server which effectively means no events caching for me anymore. 

If I'm not right, please feel free to correct me. Unfortunately, I might have a wrong idea of the mechanism how/why this is happening, but what is for sure - the problem **does exist** and as far as I see - not only for me. And if I'm right, then I think the only real solution to that would be to revert to FC4's way of options setting, which was great and I don't get it why you removed it at first place.

**Comment by notronwest** [comment] 2020-08-27 15:03
@lllopo I believe that you absolutely hit the nail on the head with your post. You are doing very similar work as we are. We have resources loaded through Vuex and events loaded through Ajax. In v.4 this worked 'Ok'. It wasn't great but it worked. In v.5 our approach did not work for the same reason - the vue data wasn't bound in the resource and event source calls. So changing a resource did not trigger the events to be reloaded.

We did create a workaround though. We load the calendar api ($refs.fullCalendar.getApi()) and tear down and rebuild resources and events whenever our data changes using getEventSources/getResources and addEventSource/addResource.

` refreshEventSources() {
        const eventSources = this.calendarApi.getEventSources()
        eventSources.forEach( source => {
          source.remove()
        })
        this.calendarApi.addEventSource(this.getAvailability())
        this.calendarApi.addEventSource(this.getEvents())
      },
      refreshResources() {
        const resources = this.calendarApi.getResources()
        resources.forEach( source => {
          source.remove()
        })
        const therapists = (this.selectedTherapists.length > 0) ? this.selectedTherapists : this.selectedTherapists
        therapists.forEach( resource => {
          this.calendarApi.addResource(resource)
        })
      }`

**Comment by lllopo** [comment] 2020-08-27 15:09
@notronwest Yup - the same. Thanks for the tip. It also will work if you as in the Vuex example - all options as one giant computed property. But then expect worse performance, even flicker if you do have a lot of things going on and of course - forget about the caching, which was working great in FC4.

**Comment by arshaw** [comment] 2020-09-01 22:34
@lllopo, I closed this ticket for administrative reasons. Too many people were talking about too many different unrelated problems and it became really hard to manage.

@lllopo and @notronwest, I changed the options API for the Vue connector in v5 because a different set of people thought there was too much duplicate code when initializing a FullCalendar, and I agreed with them. See https://github.com/fullcalendar/fullcalendar-vue/issues/47

I understand where you both are coming from when you say that changing ONE option will rerender EVERYTHING, causing performance issues. However, under the hood, that's not actually the case. FullCalendar's core is NOT written in Vue, so it's able to have more control over when to react to options changes. It attempts to be smart about it. See [here](https://github.com/fullcalendar/fullcalendar/blob/v5.3.0/packages/common/src/reducers/CalendarDataManager.ts#L430) as one example. It ignores properties that are identical. For complex properties like the `headerToolbar`, `events`, and `resources` logic, it has special cases about when to rerender. The performance hit for comparing values like this is microscopic, and absolutely no flickering should happen.

If you are seeing performance problems or bugs, please post a [runnable reduced test case](https://fullcalendar.io/reduced-test-cases) in a **separate ticket**. This ticket will no longer be monitored.

@notronwest, I know you posted reduced test case previously, but it turned out that your problem was unrelated.

**Comment by lllopo** [comment] 2020-09-02 08:30
@arshaw Unfortunately I don't have a reduced test case (quite busy, if I have the time I'll make one), but the thing is there is something wrong. Same setup, same data - different results in FC4 and FC5. Of course FC is not Vue at it's core and if you say there is special handling logic that detects only the changes when you reset the whole options object from Vue - then the problem is somewhere within this logic. I'd suggest we concentrate on the two breaking points, I've clearly detected and please, let's try sort them out as it is really a show stopper for some of us. These are :
1. (not that important) When the options object is set in any other way, but a computed property and contains other computed properties as values, it doesn't bind properly. I'm not talking for the 'undefined' errors when this is done in the `data()` function - this is normal, but I'm talking for the case, when this is done on `monted()` for example. For some reason - in this case the computed properties bound options are not reactive.
2. (!!!!!!! ... can't stress enough) The `events`, at least when set to be an ajax source, **definitely** gets rebound on **every** options set (I tracked my flickering and overall performance problems to that, btw.). This means no caching and as a consequence - performance problems. This **absolutely** for sure was not the case in FC4, so it is pretty clear the problem is somewhere in the logic you mentioned - for detecting what is changed and what's not in the options object. I can't say if this is only when the events is an ajax source or in all cases, but it's bad enough, having that ajax source is probably the most popular case anyway. Also I think this probably means, that the same issue probably exists with other options that are a function or a complex JSON object, although I don't have proof for that (gut feeling :-)).

I strongly believe the combination of these two (and maybe other stuff I don't see for now) caused the creation of this issue at first place, so it is fully relevant.

**Comment by lllopo** [comment] 2020-09-02 14:24
@arshaw I actually took the time to prepare some test cases based on one of your examples as it is really important. 
There you go for point 2 first :

[https://codesandbox.io/s/fc5-events-not-caching-fi8hm?file=/src/DemoApp.vue](https://codesandbox.io/s/fc5-events-not-caching-fi8hm?file=/src/DemoApp.vue)

It work as follows : the calendar picks a random event form a set of events through a function attached to the `events `property. So, when initially loaded some event is selected. Then, if you click the "Kick it" link below, this changes a totally unrelated property - namely the `headerToolbar`. At this point you'll probably notice that the selected event will change, while it shouldn't, of course. This not only shows the problem 2 from my post above, but also proves that it exists if the `events` is attached to a function and an ajax source (which had to be expected actually).

There it is for point 1 :

[https://codesandbox.io/s/fc5-cumputed-not-reactive-i2gqc?file=/src/DemoApp.vue](https://codesandbox.io/s/fc5-cumputed-not-reactive-i2gqc?file=/src/DemoApp.vue)

This time it is absolutely the same as the one above, with the only difference, that the calendar options are part of the `data` function. As result, while `kickitValue` is well reactive and working (printed below the link), nothing happens on the FC side, so the option is not reactive.

**Comment by arshaw** [comment] 2020-09-03 16:27
Thank you so much for these repros @lllopo. A repro is worth a thousand words. Since they are distinct issues, I've made two separate tickets:

issue 1 - https://github.com/fullcalendar/fullcalendar-vue/issues/119
issue 2 - https://github.com/fullcalendar/fullcalendar-vue/issues/120
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
