### ISSUE TITLE
[regression] eventMouseEnter and eventMouseLeave triggered repeatedly on DOM update

### ISSUE THREAD

**Issue by nsorin** [fullcalendar/fullcalendar-vue#11] opened 2019-04-23 13:48 UTC
Hello,

I noticed an issue with eventMouseEnter and eventMouseLeave when the DOM is updated in a Vue component, as you can see in [this sandbox](https://codesandbox.io/s/4nn87v110?fontsize=14).

The `test` variable is supposed to become `true` when the mouse enters an event, and `false` when the mouse leaves the event. I also added `console.log()` calls to see when the two events are fired.

As you can see in the sandbox, when the mouse enters the calendar event, both mouse events are fired repeatedly, one after the other.

More specifically, every time the DOM is updated while the mouse hovers over an event, both events are fired. If we don't display the value of `test` on top of the calendar, this does not happen and the events are fired only once as they should be.

This issue does not happen with regular `mouseenter `and `mouseleave` Vue events. To illustrate this, I added a div showing the value of a `test2` variable which updates on hover.

I am not sure if this issue happens only in the Vue implementation. I tried doing something similar in the regular version ([here](https://codepen.io/anon/pen/oOPdMW?editors=0011)) by calling `render()` in both handlers, but I don't think this is a good example as it should not be equivalent.

Thanks in advance for looking into this.

**Comment by arshaw** [comment] 2019-06-02 17:09
i figured out the problem, it was actually related to the calendar thinking it needed to rerender because it received new `header` objects on each virtual dom rerender. this is fixed in master. will release soon

**Comment by arshaw** [comment] 2019-06-03 15:53
fixed in 4.2.0: https://codesandbox.io/s/fullcalendar-vue-lscmk

https://github.com/fullcalendar/fullcalendar-vue/releases/tag/v4.2.0

**Comment by nsorin** [comment] 2019-07-19 07:28
Hi @arshaw, I noticed that the problem seems to be back in 4.2.2. I will use 4.2.0 for now, but you might want to have a look at it again.

**Comment by arshaw** [comment] 2019-07-25 03:53
You're right, this is back in @fullcalendar/vue@4.2.0
https://codesandbox.io/s/fullcalendar-vue-kbldb

I'll work on a fix

**Closed** 2019-08-12 21:33 UTC
Labels: Confirmed

**Comment by arshaw** [comment] 2019-08-12 21:35
fixed in v4.3.1

FYI- there was a bug in a test, which allowed this regression. all fixed
