### ISSUE TITLE
Class instances in extendedProps are converted to plain objects

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar-vue#53] opened 2019-10-24 07:06 UTC
In my typescript application, calendar events are modeled by an `Event` class, which not only has properites but also utility functions. In order to work with my actual `Event` instances on fullcalendar hooks, I'm embedding them using `extendedProps`.

Everything works fine when supplying the events via event sources, but I ran into issues recently when I switched to using the `events` prop. It turns out that the Vue component uses `deepCopy` on deep props such as `events`, which has the side effect of converting my `Event` objects to plain objects, obviously leading to runtime errors when trying to use any of the `Event` methods.

I'm sure there are valid reasons why the props are deep-copied in the first place, but class instances should not be converted to plain objects.

**Comment by acerix** [comment] 2019-10-25 21:56
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by dneuschaefer-rube** [comment] 2019-11-07 16:32
Here you go: https://codesandbox.io/embed/fullcalendar-vue-9f51c

As you can see when clicking the event in the calendar, the class instance I passed via `extendedProps` has been converted to a plain object, so I cannot access the methods.

**Comment by acerix** [comment] 2019-11-07 20:23
Thanks, confirmed in Vue but it works otherwise:

https://codepen.io/acerix/pen/WNNJPwr?editors=0010

Passing just a function works so you could try that as a workaround:

https://codesandbox.io/s/fullcalendar-vue-lih2n

**Comment by arshaw** [comment] 2019-11-17 21:16
yeah, our [deepCopy](https://github.com/fullcalendar/fullcalendar-vue/blob/master/src/utils.js#L8) implementation doesn't take this into account. 

would need an isPlainObject implementation. should research here: https://stackoverflow.com/questions/5876332/how-can-i-differentiate-between-an-object-literal-other-javascript-objects

**Comment by arshaw** [comment] 2020-04-14 05:58
this should be fixed in [the latest v5 beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

**Comment by arshaw** [comment] 2020-07-17 20:24
this is no longer an issue in v5: https://codesandbox.io/s/fullcalendar-vue-hzurc?file=/src/DemoApp.vue

**Closed by arshaw** 2020-07-17 20:24 UTC
Labels: Confirmed
