### ISSUE TITLE
When events are specified as a function that function never gets called

### ISSUE THREAD

**Issue by Jakuboslav** [fullcalendar/fullcalendar-vue#44] opened 2019-08-10 11:16 UTC
### Bug Reports
When I add some properties ( :header, :buttonText) to customize calendar, all app stucks (looks like endless loop). When I remove these props, app and calendar works again as intended.
It can be replicated at any time.

### Is your bug/feature applicable to the core project, without Vue?
No, it is only Vue problem, I think.

**Comment by acerix** [comment] 2019-08-12 18:01
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

The debug template specifies a `header` which is working: 

https://codesandbox.io/s/8xyz32l0r8

**Comment by Jakuboslav** [comment] 2019-08-12 21:15
I found out, that there is conenction between :header ( and others) and :datesRender.

I use :datesRender to get new events for calendar when month ( week, day) is changed.
So I have something like this:
```

<FullCalendar
    ... 
    :datesRender="getItemsByDay"
    :header"..."
    ...
/>
...
getItemsByDay(arg) {
      this.calendarEvents = [];
      axios
        .get("https://jsonplaceholder.typicode.com/posts/1")
        .then(response => {
          console.info(response);
          this.calendarEvents.push({ title: "Event Now", start: new Date() }); 
        });
    }
```


When header is not present, this event seems to be triggered only once and it is working correctly.

When header is present it seems like it is triggering all the time and the app stucks.

I was able to replicate it in your debug template only partly, when I used push() directly on calendarEvents.

In my case it happens even if I replace old array with items with new array, but I could not replicate it in debug template.

https://codesandbox.io/s/fullcalendar-vue-vj5zo?fontsize=14

**Comment by acerix** [comment] 2019-08-13 18:14
It sounds like the issue comes from datesRender getting stuck in a loop, which could be from how you are adding the events, although I don't get that in your demo.  

To add events from an external source, you should supply them in a function as described here:

https://fullcalendar.io/docs/events-function

That way the events are fetched automatically when the dates change and should avoid the loop problem.

**Comment by Jakuboslav** [comment] 2019-08-13 20:38
Hello,
events function helped me a little bit, since now app doesn't stuck.

At this moment calendar is looped and it is triggering **dayRender** infinitely() and no events are shown in calendar. Event function is called all the time, without any clear explanation.

I used same implemetation as mentioned in your link, but in my environment.

Is it possible to find out any possible source of this behaviour?

**Comment by acerix** [comment] 2019-08-13 22:42
If you can make a demo in the debug template or provide instructions to reproduce the issue we can look into it. Since you are supplying the events from the function now, you don't need to use `datesRender` for that so I think you can remove `datesRender` which might fix it.

**Comment by Jakuboslav** [comment] 2019-08-14 12:05
Hello, 
I removed **datesRender** when I used event function for event supplying, so it is not cause of infinite loop. 

I attach simplified version of my implemetation. For some reason I have to add brackets in **:events="getEvents"** to make method be called, that doesn't make sense to me.

If you use this implementation in your environment it should behave in the same way as I descripted above.

https://codesandbox.io/s/fullcalendar-vue-yt3yv?fontsize=14

**Comment by acerix** [comment] 2019-08-14 20:45
I don't see any loop in your demo but it looks like "events as a function" is not working in Vue.

https://codesandbox.io/s/fullcalendar-vue-7mpk9

The option should be specified like `@events="getEvents"` since it's a method.  `:events="getEvents()"` works because that is assigning the result of the function instead of the function itself.

If your server is returning events in the normal JSON format you could supply just the URL instead which should work:

https://fullcalendar.io/docs/events-json-feed

**Comment by ultrono** [comment] 2020-03-17 15:20
I"m getting a similar issue using https://fullcalendar.io/docs/events-function, events never get set. This worked fine with the old verions at https://fullcalendar.io/docs/v3/events-function#v2. IS there a known fix for this?

**Comment by arshaw** [comment] 2020-06-22 22:57
it seems like the problem was related to specifying `:events` incorrectly

**Closed by arshaw** 2020-06-22 22:57 UTC
Labels: Confirmed
